site_name: Actual Python

dev_addr: '127.0.0.1:8500'

repo_url: https://github.com/achianumba/actual-python
repo_name: GitHub
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Arinze Chianumba

# exclude_docs: |
#   *.py
#   .gitignore
  # /requirements.txt
# /venv:working_dir:

theme:
  name: material

  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# extra_css:
#   - css/main.css

markdown_extensions:
  smarty: {}
  sane_lists: {}
  admonition: {}
  # git-revision-date-localized:
  #   enabled: true
  #   enable_creation_date: true
  #   type: date 
  # git-committers:
  #   enabled: true
  #   branch: main
  #   repository: achianumba/actual-python
  # git-authors: {}

nav:
  - 'Getting Started': index.md
  - Setup: 
    - setup/index.md
    - 'Install Python': setup/install-python.md
    - 'Install a Code Editor': 'setup/install-code-editor.md'
