name: Deploy Site

on:
  push:
    branches:
      - main
    # Run this workflow manually from the Actions tab on GitHub.
    workflow_dispatch:

jobs:
  # Build the site
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        # with:
          # python-version: is resolved from .python-version file 

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        
      - name: Build the site
        run: uv run mkdocs build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  # Deploy site to GH Pages
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
